### ISSUE TITLE
Publish a package

### ISSUE THREAD

**Issue by andrey-helldar** [Laravel-Lang/http-statuses#1]
@caouecs, hi!

I decided to move my [`andrey-helldar/lang-translations`](https://github.com/andrey-helldar/lang-translations) package to the [`laravel-lang/http-statuses`](https://github.com/Laravel-Lang/http-statuses) namespace.

Can you publish a version on [`packagist.org`](https://packagist.org)?

**Comment by caouecs** [comment]
done https://packagist.org/packages/laravel-lang/http-statuses

**Comment by andrey-helldar** [comment]
Merci 😊

I thought that my package was named incorrectly and decided to rename it and put it in the correct place 😁

**Comment by andrey-helldar** [comment]
When I have more free time, I will move the documentation compilation code from Laravel-Lang/Lang into an external project and it can be used by any project in our team 😎
